name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Build
      run: |
        msbuild WheresMyKombucha/WheresMyKombucha.sln $BUILD_VERBOSITY /t:Build /p:Platform=iPhoneSimulator /p:Configuration=Debug
